import "server-only";

export const uiText = {
  appTitle: "Quản lý kho",
  appDescription: "MIMS quản lý luồng tồn kho cho Kho Tổng và Kho Lẻ.",
  locationsLabel: "Kho",
  greeting: "Chào",
  signOut: "Đăng xuất",
  dashboard: "Tổng quan",
  products: "Sản phẩm",
  productsNavLabel: "Tạo giỏ xuất",
  suppliers: "Nhà cung cấp",
  inbound: "Nhập kho",
  inventory: "Tồn kho",
  warehouseAccounting: "Kế toán kho",
  accountingOutbound: "Xuất kho",
  accountingInbound: "Nhập kho",
  accountingFlow: "Luồng hàng",
  accountingCustomerFlow: "Kho Lẻ → Khách hàng",
  accountingTransferFlow: "Kho Tổng → Kho Lẻ",
  accountingSupplierFlow: "NCC → Kho Tổng",
  accountingFrom: "Từ ngày",
  accountingTo: "Đến ngày",
  accountingApply: "Xem báo cáo",
  accountingExport: "Xuất CSV",
  accountingReportType: "Loại báo cáo",
  accountingCsvFlow: "Luồng",
  accountingGross: "Tổng xuất bán",
  accountingReturns: "Hàng hoàn / trả",
  accountingNet: "Xuất ròng",
  accountingReturnKind: "Loại hoàn/trả",
  accountingReturnAll: "Tất cả",
  accountingHoan: "Hàng hoàn",
  accountingTra: "Hàng trả",
  accountingGrossQuantity: "Số lượng xuất",
  accountingReturnQuantity: "Số lượng hoàn/trả",
  accountingNetQuantity: "Số lượng xuất ròng",
  accountingGrossQuantityShort: "SL xuất",
  accountingReturnQuantityShort: "SL hoàn/trả",
  accountingNetQuantityShort: "SL xuất ròng",
  accountingHoanQuantity: "Số lượng hoàn",
  accountingTraQuantity: "Số lượng trả",
  accountingTotalReturns: "Tổng hoàn/trả",
  accountingGrossValue: "Giá trị xuất",
  accountingReturnValue: "Giá trị hoàn/trả",
  accountingNetValue: "Giá trị ròng",
  accountingNetNote: "Xuất ròng = Tổng xuất bán - Hàng hoàn/trả trong cùng khoảng thời gian.",
  accountingPeriodNote: "Hàng hoàn/trả được tính vào kỳ nhận lại hàng, không phụ thuộc ngày bán ban đầu. Xuất ròng có thể âm.",
  accountingSupplierNote: "Nhập từ NCC không bao gồm hàng hoàn/trả và nhập điều chỉnh.",
  accountingDateHint: "Tối đa 60 ngày lịch, tính cả ngày đầu và ngày cuối. Ngày theo giờ Việt Nam (UTC+07).",
  accountingCostNote: "Giá trị được tính theo giá vốn hiện tại của sản phẩm.",
  accountingTotalQuantity: "Tổng số lượng",
  accountingTotalValue: "Tổng giá trị",
  accountingCurrentCost: "Giá vốn hiện tại",
  accountingEmpty: "Không có dữ liệu trong khoảng thời gian đã chọn.",
  accountingInvalidParameters: "Bộ lọc không hợp lệ. Hãy chọn đúng chế độ và luồng hàng; chỉ truyền mỗi bộ lọc một lần.",
  accountingInvalidDate: "Vui lòng nhập ngày hợp lệ theo định dạng YYYY-MM-DD.",
  accountingDateOrder: "Từ ngày phải trước hoặc bằng Đến ngày.",
  accountingDateLimit: "Vui lòng chọn tối đa 60 ngày lịch, tính cả ngày đầu và ngày cuối.",
  basket: "Xuất hàng",
  manageUsers: "Quản lý người dùng",
  admin: "Quản trị",
  operation: "Vận hành",
  exportStock: "Xuất CSV tồn kho",
  exportSuppliers: "Xuất CSV nhà cung cấp",
  exportOrders: "Xuất CSV đơn hàng",
  exportInventory: "Xuất CSV giám sát tồn kho",
  allowedStockFlow: "Luồng hàng hợp lệ",
  flow1: "Nhà sản xuất -> Kho Tổng",
  flow2: "Kho Tổng -> Kho Lẻ",
  flow3: "Kho Lẻ -> Khách hàng",
  dashboardTitle: "Bảng theo dõi kho",
  dashboardBody: "Theo dõi tồn thấp so với nhu cầu gần đây và thời gian cung ứng của nhà cung cấp.",
  totalProducts: "Tổng sản phẩm",
  lowStockItems: "Mặt hàng cần theo dõi",
  inbound30d: "Phiếu nhập 30 ngày",
  customerOrders30d: "Phiếu xuất 30 ngày",
  monitorTitle: "Danh sách cảnh báo tồn kho",
  monitorBody: "Tồn thấp, đơn gần đây cao và thời gian cung ứng dài sẽ được ưu tiên hiển thị.",
  product: "Sản phẩm",
  supplier: "Nhà cung cấp",
  khoTong: "Kho Tổng",
  khoLe: "Kho Lẻ",
  total: "Tổng",
  outbound7d: "Xuất 7 ngày",
  outbound30d: "Xuất 30 ngày",
  leadTimeDays: "Thời gian cung ứng",
  risk: "Mức độ",
  high: "Cao",
  medium: "Trung bình",
  normal: "Bình thường",
  daySuffix: "ngày",
  noInventoryRows: "Chưa có dữ liệu tồn kho trong Neon.",
  catalogManagement: "Quản lý danh mục",
  createProduct: "Tạo sản phẩm",
  newCatalogItem: "Mặt hàng mới",
  createSupplier: "Tạo nhà cung cấp",
  supplierForm: "Biểu mẫu nhà cung cấp",
  supplierMaster: "Danh mục nhà cung cấp",
  basicFieldsOnly: "Trường cơ bản",
  saveProduct: "Lưu sản phẩm",
  saveSupplier: "Lưu nhà cung cấp",
  searchSupplierContactEmailAddress: "Tìm nhà cung cấp, liên hệ, email hoặc địa chỉ",
  searchSupplierPrompt: "Bấm tìm để hiển thị nhà cung cấp.",
  searchProductOrSku: "Tìm sản phẩm hoặc SKU",
  searchWarehouse: "Kho tìm kiếm",
  allLocations: "Tất cả kho",
  allSuppliers: "Tất cả nhà cung cấp",
  includeInactive: "Bao gồm ngưng hoạt động",
  search: "Tìm",
  status: "Trạng thái",
  active: "Đang hoạt động",
  inactive: "Ngưng hoạt động",
  obsolete: "Ngưng kinh doanh",
  currentCatalog: "Danh mục hiện hành",
  basketAction: "Giỏ xuất",
  addToBasket: "Thêm vào giỏ",
  inboundReceiving: "Nhập kho",
  receiveIntoKhoTong: "Nhập vào Kho Tổng",
  outboundBasket: "Giỏ xuất hàng",
  inventoryManagement: "Quản lý tồn kho",
  currentStockPosition: "Tình hình tồn hiện tại",
  sortedBy: "Sắp xếp theo tổng tồn tăng dần, sau đó theo xuất 30 ngày giảm dần.",
  quantity: "Số lượng",
  destination: "Điểm đến",
  note: "Ghi chú",
  noInboundRows: "Chưa có phiếu nhập từ nhà sản xuất trong Neon.",
  addInboundBatch: "Thêm lô nhập kho",
  multiLineForm: "Biểu mẫu nhiều dòng",
  submitInboundBatch: "Nhập kho",
  productLookupPlaceholder: "Gõ tên sản phẩm hoặc SKU",
  selectProductFromList: "Hãy chọn sản phẩm từ danh sách gợi ý.",
  addRow: "Thêm dòng",
  inboundHistory: "Lịch sử nhập kho",
  available: "Tồn khả dụng",
  noBasketRows: "Chưa có lịch sử xuất hàng trong Neon.",
  source: "Nguồn",
  basketValidationHint: "Khi gửi phải tạo giao dịch CUSTOMER_OUT và từ chối mọi số lượng làm cho Kho Lẻ xuống dưới 0.",
  confirmIssue: "Xác nhận xuất hàng",
  currentBasket: "Giỏ hàng hiện tại",
  outboundHistory: "Lịch sử xuất hàng",
  basketEmpty: "Chưa có sản phẩm nào trong giỏ hàng.",
  remove: "Bỏ khỏi giỏ",
  clearBasket: "Xóa toàn bộ giỏ",
  totalBasketItems: "Tổng số lượng",
  searchPrompt: "Bấm tìm để hiển thị sản phẩm.",
  noProductMatches: "Không có sản phẩm nào khớp nội dung tìm kiếm.",
  noProductsRows: "Chưa có sản phẩm nào trong Neon.",
  loadMore: "Tải thêm",
  searching: "Đang tìm...",
  exceedsStockMessage: "Số lượng vượt quá tồn kho hiện có.",
  addedToBasketMessage: "Đã thêm vào giỏ hàng.",
  selectWarehouseForBasket: "Hãy chọn kho trước khi thêm vào giỏ hàng.",
  loginTitle: "Đăng nhập",
  loginBody: "Bắt buộc đăng nhập trước khi dùng ứng dụng.",
  username: "Tên đăng nhập",
  password: "Mật khẩu",
  signIn: "Đăng nhập",
  signingIn: "Đang đăng nhập...",
  submit: "Gửi",
  submitting: "Đang gửi...",
  manageUsersTitle: "Quản lý người dùng",
  adminOnly: "Chỉ quản trị",
  createUser: "Tạo người dùng",
  email: "Email",
  contact: "Liên hệ",
  phone: "Điện thoại",
  address: "Địa chỉ",
  actions: "Thao tác",
  update: "Cập nhật",
  updateSupplier: "Cập nhật nhà cung cấp",
  contactPerson: "Người liên hệ",
  role: "Vai trò",
  saveUser: "Lưu người dùng",
  created: "Ngày tạo",
  resetPassword: "Đặt lại mật khẩu",
  resetPasswordButton: "Thiết lập mật khẩu mới",
  newPasswordPlaceholder: "Nhập mật khẩu tạm thời",
  loginIdPlaceholder: "Mã đăng nhập",
  temporaryPasswordPlaceholder: "Mật khẩu tạm thời",
  sku: "SKU",
  costPrice: "Giá thành",
  enterProductName: "Nhập tên sản phẩm",
  enterSku: "Nhập SKU",
  enterCostPrice: "Nhập giá thành",
  enterSupplierName: "Nhập tên nhà cung cấp",
  contactPersonPlaceholder: "Người liên hệ",
  phoneNumberPlaceholder: "Số điện thoại",
  emailAddressPlaceholder: "Địa chỉ email",
  basicSupplierAddressPlaceholder: "Địa chỉ cơ bản của nhà cung cấp",
  paymentTerms: "Điều khoản thanh toán",
  paymentTermsPlaceholder: "Nhập điều khoản thanh toán",
  deliveryMethod: "Phương thức giao hàng",
  deliveryMethodPlaceholder: "Nhập phương thức giao hàng",
  pastIssues: "Vấn đề từng phát sinh",
  pastIssuesPlaceholder: "Nhập vấn đề từng phát sinh",
  selectSupplier: "Chọn nhà cung cấp",
  noSuppliersRows: "Chưa có nhà cung cấp nào trong Neon.",
  noSupplierMatches: "Không có nhà cung cấp nào khớp nội dung tìm kiếm.",
  usernameTaken: "Tên đăng nhập này đã tồn tại.",
  productCreateSuccess: "Lưu sản phẩm thành công.",
  productCreateError: "Không thể lưu sản phẩm.",
  productSkuTaken: "Mã SKU này đã tồn tại.",
  supplierCreateSuccess: "Lưu nhà cung cấp thành công.",
  supplierCreateError: "Không thể lưu nhà cung cấp.",
  supplierUpdateSuccess: "Cập nhật nhà cung cấp thành công.",
  supplierUpdateError: "Không thể cập nhật nhà cung cấp.",
  userCreateSuccess: "Lưu người dùng thành công.",
  userCreateError: "Không thể lưu người dùng.",
  passwordResetSuccess: "Cập nhật mật khẩu thành công.",
  passwordResetError: "Không thể cập nhật mật khẩu.",
  edit: "Sửa",
  updateProduct: "Cập nhật sản phẩm",
  updateProductSuccess: "Cập nhật sản phẩm thành công.",
  updateProductError: "Không thể cập nhật sản phẩm.",
  inboundSubmitSuccess: "Gửi lô nhập kho thành công.",
  inboundSubmitError: "Không thể gửi lô nhập kho.",
  basketSubmitSuccess: "Xuất hàng thành công.",
  basketSubmitError: "Không thể xuất hàng.",
  basketStockError: "Có sản phẩm vượt quá tồn kho hiện có.",
} as const;
