import "server-only";

import { cookies } from "next/headers";
import { uiCookieNames, type UiLanguage, type UiTheme } from "@/lib/ui-preferences";

const dictionaries = {
  en: {
    appTitle: "Warehouse Control",
    appDescription: "Neon-backed stock flow for Kho Tổng and Kho Lẻ.",
    workspaceLabel: "Warehouse workspace",
    locationsLabel: "Locations",
    signedInAs: "Signed in as",
    greeting: "Hi",
    signOut: "Sign out",
    dashboard: "Dashboard",
    products: "Products",
    suppliers: "Suppliers",
    inbound: "Inbound",
    inventory: "Inventory",
    basket: "Basket",
    manageUsers: "Manage Users",
    admin: "Admin",
    operation: "Operation",
    lightMode: "Light",
    darkMode: "Dark",
    english: "EN",
    vietnamese: "VN",
    exportStock: "Export Stock CSV",
    exportSuppliers: "Export Supplier CSV",
    exportOrders: "Export Order CSV",
    exportInventory: "Export Inventory CSV",
    allowedStockFlow: "Allowed stock flow",
    flow1: "Manufacturer -> Kho Tổng",
    flow2: "Kho Tổng -> Kho Lẻ",
    flow3: "Kho Lẻ -> Customer",
    dashboardTitle: "Warehouse dashboard",
    dashboardBody: "Track low stock against recent customer demand and supplier lead time.",
    totalProducts: "Total products",
    lowStockItems: "Low stock items",
    inbound30d: "Inbound receipts 30d",
    customerOrders30d: "Customer orders 30d",
    monitorTitle: "Stock risk watchlist",
    monitorBody: "Low total stock, higher recent orders, and long lead time rise to the top.",
    product: "Product",
    supplier: "Supplier",
    khoTong: "Kho Tổng",
    khoLe: "Kho Lẻ",
    total: "Total",
    outbound7d: "Orders 7d",
    outbound30d: "Orders 30d",
    leadTimeDays: "Lead time",
    risk: "Risk",
    high: "High",
    medium: "Medium",
    normal: "Normal",
    daySuffix: "days",
    noInventoryRows: "No inventory rows in Neon yet.",
    catalogManagement: "Catalog management",
    createProduct: "Create product",
    newCatalogItem: "New catalog item",
    productImageUrl: "Product image URL",
    collapsedByDefault: "Collapsed by default",
    createSupplier: "Create new supplier",
    supplierForm: "Supplier form",
    supplierMaster: "Supplier master",
    basicFieldsOnly: "Basic fields only",
    saveProduct: "Save product",
    saveSupplier: "Save supplier",
    searchProductOrSku: "Search product or SKU",
    allSuppliers: "All suppliers",
    includeInactive: "Include inactive",
    search: "Search",
    status: "Status",
    active: "Active",
    inactive: "Inactive",
    obsolete: "Obsolete",
    currentCatalog: "Current catalog",
    basketAction: "Basket",
    addToBasket: "Add to basket",
    inboundReceiving: "Inbound receiving",
    receiveIntoKhoTong: "Receive into Kho Tổng",
    outboundBasket: "Outbound basket",
    issueFromKhoLe: "Issue from Kho Lẻ",
    inventoryManagement: "Inventory management",
    currentStockPosition: "Current stock position",
    sortedBy: "Sorted by total stock ascending, then 30-day outbound descending.",
    loginTitle: "Sign in to Warehouse Control",
    loginBody: "A login is required before using this application.",
    username: "Username",
    password: "Password",
    signIn: "Sign in",
    signingIn: "Signing in...",
    defaultAdmin: "Default seeded admin account",
    manageUsersTitle: "Manage users",
    adminOnly: "Admin only",
    createUser: "Create user",
    fullName: "Full name",
    email: "Email",
    role: "Role",
    saveUser: "Save user",
    created: "Created",
    resetPassword: "Reset password",
    resetPasswordButton: "Set new password",
    newPasswordPlaceholder: "Enter a temporary password",
  },
  vi: {
    appTitle: "Điều phối kho",
    appDescription: "Luồng tồn kho dùng Neon cho Kho Tổng và Kho Lẻ.",
    workspaceLabel: "Không gian vận hành kho",
    locationsLabel: "Kho",
    signedInAs: "Đăng nhập bởi",
    greeting: "Chào",
    signOut: "Đăng xuất",
    dashboard: "Tổng quan",
    products: "Sản phẩm",
    suppliers: "Nhà cung cấp",
    inbound: "Nhập kho",
    inventory: "Tồn kho",
    basket: "Xuất hàng",
    manageUsers: "Quản lý người dùng",
    admin: "Quản trị",
    operation: "Vận hành",
    lightMode: "Sáng",
    darkMode: "Tối",
    english: "EN",
    vietnamese: "VN",
    exportStock: "Xuất CSV tồn kho",
    exportSuppliers: "Xuất CSV nhà cung cấp",
    exportOrders: "Xuất CSV đơn hàng",
    exportInventory: "Xuất CSV giám sát tồn kho",
    allowedStockFlow: "Luồng hàng hợp lệ",
    flow1: "Nhà sản xuất -> Kho Tổng",
    flow2: "Kho Tổng -> Kho Lẻ",
    flow3: "Kho Lẻ -> Khách hàng",
    dashboardTitle: "Bảng theo dõi kho",
    dashboardBody: "Theo dõi tồn thấp so với nhu cầu gần đây và thời gian cung ứng của nhà cung cấp.",
    totalProducts: "Tổng sản phẩm",
    lowStockItems: "Mặt hàng cần theo dõi",
    inbound30d: "Phiếu nhập 30 ngày",
    customerOrders30d: "Phiếu xuất 30 ngày",
    monitorTitle: "Danh sách cảnh báo tồn kho",
    monitorBody: "Tồn thấp, đơn gần đây cao và lead time dài sẽ được ưu tiên hiển thị.",
    product: "Sản phẩm",
    supplier: "Nhà cung cấp",
    khoTong: "Kho Tổng",
    khoLe: "Kho Lẻ",
    total: "Tổng",
    outbound7d: "Đơn 7 ngày",
    outbound30d: "Đơn 30 ngày",
    leadTimeDays: "Lead time",
    risk: "Mức độ",
    high: "Cao",
    medium: "Trung bình",
    normal: "Bình thường",
    daySuffix: "ngày",
    noInventoryRows: "Chưa có dữ liệu tồn kho trong Neon.",
    catalogManagement: "Quản lý danh mục",
    createProduct: "Tạo sản phẩm",
    newCatalogItem: "Mặt hàng mới",
    productImageUrl: "Đường dẫn ảnh sản phẩm",
    collapsedByDefault: "Mặc định thu gọn",
    createSupplier: "Tạo nhà cung cấp",
    supplierForm: "Biểu mẫu nhà cung cấp",
    supplierMaster: "Danh mục nhà cung cấp",
    basicFieldsOnly: "Trường cơ bản",
    saveProduct: "Lưu sản phẩm",
    saveSupplier: "Lưu nhà cung cấp",
    searchProductOrSku: "Tìm sản phẩm hoặc SKU",
    allSuppliers: "Tất cả nhà cung cấp",
    includeInactive: "Bao gồm ngưng hoạt động",
    search: "Tìm",
    status: "Trạng thái",
    active: "Đang dùng",
    inactive: "Ngưng dùng",
    obsolete: "Ngưng kinh doanh",
    currentCatalog: "Danh mục hiện hành",
    basketAction: "Giỏ xuất",
    addToBasket: "Thêm vào giỏ",
    inboundReceiving: "Nhập kho",
    receiveIntoKhoTong: "Nhập vào Kho Tổng",
    outboundBasket: "Giỏ xuất hàng",
    issueFromKhoLe: "Xuất từ Kho Lẻ",
    inventoryManagement: "Quản lý tồn kho",
    currentStockPosition: "Tình hình tồn hiện tại",
    sortedBy: "Sắp xếp theo tổng tồn tăng dần, sau đó theo xuất 30 ngày giảm dần.",
    loginTitle: "Đăng nhập vào Điều phối kho",
    loginBody: "Bắt buộc đăng nhập trước khi dùng ứng dụng.",
    username: "Tên đăng nhập",
    password: "Mật khẩu",
    signIn: "Đăng nhập",
    signingIn: "Đang đăng nhập...",
    defaultAdmin: "Tài khoản quản trị mặc định",
    manageUsersTitle: "Quản lý người dùng",
    adminOnly: "Chỉ quản trị",
    createUser: "Tạo người dùng",
    fullName: "Họ tên",
    email: "Email",
    role: "Vai trò",
    saveUser: "Lưu người dùng",
    created: "Ngày tạo",
    resetPassword: "Đặt lại mật khẩu",
    resetPasswordButton: "Thiết lập mật khẩu mới",
    newPasswordPlaceholder: "Nhập mật khẩu tạm thời",
  },
} as const;

export async function getUiPreferences() {
  const cookieStore = await cookies();
  const theme = cookieStore.get(uiCookieNames.theme)?.value === "dark" ? "dark" : "light";
  const language = cookieStore.get(uiCookieNames.language)?.value === "vi" ? "vi" : "en";

  return {
    theme,
    language,
  } satisfies { theme: UiTheme; language: UiLanguage };
}

export async function getUiContext() {
  const preferences = await getUiPreferences();

  return {
    ...preferences,
    text: dictionaries[preferences.language],
  };
}

