import "server-only";

import { cookies } from "next/headers";
import { legacyUiCookieNames, uiCookieNames, type UiLanguage, type UiTheme } from "@/lib/ui-preferences";

const dictionaries = {
  en: {
    appTitle: "Warehouse App",
    appDescription: "MIMS stock flow for Kho Tổng and Kho Lẻ.",
    locationsLabel: "Locations",
    greeting: "Hi",
    signOut: "Sign out",
    dashboard: "Dashboard",
    products: "Products",
    suppliers: "Suppliers",
    inbound: "Inbound",
    inventory: "Inventory",
    basket: "Basket",
    manageUsers: "Manage Users",
    admin: "Admin",
    operation: "Operation",
    lightMode: "Light",
    darkMode: "Dark",
    english: "EN",
    vietnamese: "VN",
    exportStock: "Export Stock CSV",
    exportSuppliers: "Export Supplier CSV",
    exportOrders: "Export Order CSV",
    exportInventory: "Export Inventory CSV",
    allowedStockFlow: "Allowed stock flow",
    flow1: "Manufacturer -> Kho Tổng",
    flow2: "Kho Tổng -> Kho Lẻ",
    flow3: "Kho Lẻ -> Customer",
    dashboardTitle: "Warehouse dashboard",
    dashboardBody: "Track low stock against recent customer demand and supplier lead time.",
    totalProducts: "Total products",
    lowStockItems: "Low stock items",
    inbound30d: "Inbound receipts 30d",
    customerOrders30d: "Customer orders 30d",
    monitorTitle: "Stock risk watchlist",
    monitorBody: "Low total stock, higher recent orders, and long lead time rise to the top.",
    product: "Product",
    supplier: "Supplier",
    khoTong: "Kho Tổng",
    khoLe: "Kho Lẻ",
    total: "Total",
    outbound7d: "Orders 7d",
    outbound30d: "Orders 30d",
    leadTimeDays: "Lead time",
    risk: "Risk",
    high: "High",
    medium: "Medium",
    normal: "Normal",
    daySuffix: "days",
    noInventoryRows: "No inventory rows in Neon yet.",
    catalogManagement: "Catalog management",
    createProduct: "Create product",
    newCatalogItem: "New catalog item",
    createSupplier: "Create new supplier",
    supplierForm: "Supplier form",
    supplierMaster: "Supplier master",
    basicFieldsOnly: "Basic fields only",
    saveProduct: "Submit",
    saveSupplier: "Submit",
    searchProductOrSku: "Search product or SKU",
    image: "Image",
    noImage: "No image",
    searchWarehouse: "Warehouse",
    allLocations: "All locations",
    allSuppliers: "All suppliers",
    includeInactive: "Include inactive",
    search: "Search",
    status: "Status",
    active: "Active",
    inactive: "Deactive",
    obsolete: "Obsolete",
    currentCatalog: "Current catalog",
    basketAction: "Basket",
    addToBasket: "Add to basket",
    inboundReceiving: "Inbound receiving",
    receiveIntoKhoTong: "Receive into Kho Tổng",
    outboundBasket: "Outbound basket",
    inventoryManagement: "Inventory management",
    currentStockPosition: "Current stock position",
    sortedBy: "Sorted by total stock ascending, then 30-day outbound descending.",
    quantity: "Quantity",
    destination: "Destination",
    note: "Note",
    noInboundRows: "No manufacturer receipts in Neon yet.",
    addInboundBatch: "Add inbound batch",
    multiLineForm: "Multi-line form",
    submitInboundBatch: "Submit",
    productLookupPlaceholder: "Type product name or SKU",
    selectProductFromList: "Select a product from the suggestion list.",
    addRow: "Add row",
    inboundHistory: "Inbound history",
    available: "Available",
    noBasketRows: "No outbound history in Neon yet.",
    source: "Source",
    basketValidationHint: "Submission should create CUSTOMER_OUT transactions and reject any quantity that would push Kho Lẻ below zero.",
    confirmIssue: "Submit",
    currentBasket: "Current basket",
    outboundHistory: "Outbound history",
    basketEmpty: "No items in the basket yet.",
    remove: "Remove",
    clearBasket: "Clear basket",
    totalBasketItems: "Total items",
    searchPrompt: "Search to show products.",
    noProductMatches: "No products match the current search.",
    noProductsRows: "No products in Neon yet.",
    exceedsStockMessage: "Quantity exceeds available stock.",
    addedToBasketMessage: "Added to basket.",
    selectWarehouseForBasket: "Select a warehouse before adding to basket.",
    loginTitle: "Sign in",
    loginBody: "A login is required before using this application.",
    username: "Username",
    password: "Password",
    signIn: "Sign in",
    signingIn: "Signing in...",
    submit: "Submit",
    submitting: "Submitting...",
    manageUsersTitle: "Manage users",
    adminOnly: "Admin only",
    createUser: "Create user",
    email: "Email",
    contact: "Contact",
    phone: "Phone",
    address: "Address",
    actions: "Actions",
    update: "Update",
    updateSupplier: "Update supplier",
    contactPerson: "Contact person",
    role: "Role",
    saveUser: "Submit",
    created: "Created",
    resetPassword: "Reset password",
    resetPasswordButton: "Set new password",
    newPasswordPlaceholder: "Enter a temporary password",
    loginIdPlaceholder: "Login ID",
    temporaryPasswordPlaceholder: "Temporary password",
    enterProductName: "Enter product name",
    enterSupplierName: "Enter supplier name",
    contactPersonPlaceholder: "Contact person",
    phoneNumberPlaceholder: "Phone number",
    emailAddressPlaceholder: "Email address",
    basicSupplierAddressPlaceholder: "Basic supplier address",
    productImageUpload: "Upload product image",
    selectSupplier: "Select supplier",
    noSuppliersRows: "No suppliers in Neon yet.",
    usernameTaken: "This username already exists.",
    productCreateSuccess: "Product saved successfully.",
    productCreateError: "Unable to save product.",
    supplierCreateSuccess: "Supplier saved successfully.",
    supplierCreateError: "Unable to save supplier.",
    supplierUpdateSuccess: "Supplier updated successfully.",
    supplierUpdateError: "Unable to update supplier.",
    userCreateSuccess: "User saved successfully.",
    userCreateError: "Unable to save user.",
    passwordResetSuccess: "Password updated successfully.",
    passwordResetError: "Unable to update password.",
    edit: "Edit",
    updateProduct: "Update product",
    updateProductSuccess: "Product updated successfully.",
    updateProductError: "Unable to update product.",
    invalidImageMessage: "Invalid image file.",
    inboundSubmitSuccess: "Inbound batch submitted successfully.",
    inboundSubmitError: "Unable to submit inbound batch.",
    basketSubmitSuccess: "Basket submitted successfully.",
    basketSubmitError: "Unable to submit basket.",
    basketStockError: "One or more basket items exceed available stock.",
  },
  vi: {
    appTitle: "Warehouse App",
    appDescription: "MIMS quản lý luồng tồn kho cho Kho Tổng và Kho Lẻ.",
    locationsLabel: "Kho",
    greeting: "Chào",
    signOut: "Đăng xuất",
    dashboard: "Tổng quan",
    products: "Sản phẩm",
    suppliers: "Nhà cung cấp",
    inbound: "Nhập kho",
    inventory: "Tồn kho",
    basket: "Xuất hàng",
    manageUsers: "Quản lý người dùng",
    admin: "Quản trị",
    operation: "Vận hành",
    lightMode: "Sáng",
    darkMode: "Tối",
    english: "EN",
    vietnamese: "VN",
    exportStock: "Xuất CSV tồn kho",
    exportSuppliers: "Xuất CSV nhà cung cấp",
    exportOrders: "Xuất CSV đơn hàng",
    exportInventory: "Xuất CSV giám sát tồn kho",
    allowedStockFlow: "Luồng hàng hợp lệ",
    flow1: "Nhà sản xuất -> Kho Tổng",
    flow2: "Kho Tổng -> Kho Lẻ",
    flow3: "Kho Lẻ -> Khách hàng",
    dashboardTitle: "Bảng theo dõi kho",
    dashboardBody: "Theo dõi tồn thấp so với nhu cầu gần đây và thời gian cung ứng của nhà cung cấp.",
    totalProducts: "Tổng sản phẩm",
    lowStockItems: "Mặt hàng cần theo dõi",
    inbound30d: "Phiếu nhập 30 ngày",
    customerOrders30d: "Phiếu xuất 30 ngày",
    monitorTitle: "Danh sách cảnh báo tồn kho",
    monitorBody: "Tồn thấp, đơn gần đây cao và lead time dài sẽ được ưu tiên hiển thị.",
    product: "Sản phẩm",
    supplier: "Nhà cung cấp",
    khoTong: "Kho Tổng",
    khoLe: "Kho Lẻ",
    total: "Tổng",
    outbound7d: "Đơn 7 ngày",
    outbound30d: "Đơn 30 ngày",
    leadTimeDays: "Lead time",
    risk: "Mức độ",
    high: "Cao",
    medium: "Trung bình",
    normal: "Bình thường",
    daySuffix: "ngày",
    noInventoryRows: "Chưa có dữ liệu tồn kho trong Neon.",
    catalogManagement: "Quản lý danh mục",
    createProduct: "Tạo sản phẩm",
    newCatalogItem: "Mặt hàng mới",
    createSupplier: "Tạo nhà cung cấp",
    supplierForm: "Biểu mẫu nhà cung cấp",
    supplierMaster: "Danh mục nhà cung cấp",
    basicFieldsOnly: "Trường cơ bản",
    saveProduct: "Submit",
    saveSupplier: "Submit",
    searchProductOrSku: "Tìm sản phẩm hoặc SKU",
    image: "Hình ảnh",
    noImage: "No image",
    searchWarehouse: "Kho tìm kiếm",
    allLocations: "Tất cả kho",
    allSuppliers: "Tất cả nhà cung cấp",
    includeInactive: "Bao gồm ngưng hoạt động",
    search: "Tìm",
    status: "Trạng thái",
    active: "Active",
    inactive: "Deactive",
    obsolete: "Ngưng kinh doanh",
    currentCatalog: "Danh mục hiện hành",
    basketAction: "Giỏ xuất",
    addToBasket: "Thêm vào giỏ",
    inboundReceiving: "Nhập kho",
    receiveIntoKhoTong: "Nhập vào Kho Tổng",
    outboundBasket: "Giỏ xuất hàng",
    inventoryManagement: "Quản lý tồn kho",
    currentStockPosition: "Tình hình tồn hiện tại",
    sortedBy: "Sắp xếp theo tổng tồn tăng dần, sau đó theo xuất 30 ngày giảm dần.",
    quantity: "Số lượng",
    destination: "Điểm đến",
    note: "Ghi chú",
    noInboundRows: "Chưa có phiếu nhập từ nhà sản xuất trong Neon.",
    addInboundBatch: "Thêm lô nhập kho",
    multiLineForm: "Biểu mẫu nhiều dòng",
    submitInboundBatch: "Submit",
    productLookupPlaceholder: "Gõ tên sản phẩm hoặc SKU",
    selectProductFromList: "Hãy chọn sản phẩm từ danh sách gợi ý.",
    addRow: "Thêm dòng",
    inboundHistory: "Lịch sử nhập kho",
    available: "Tồn khả dụng",
    noBasketRows: "Chưa có lịch sử xuất hàng trong Neon.",
    source: "Nguồn",
    basketValidationHint: "Khi gửi phải tạo giao dịch CUSTOMER_OUT và từ chối mọi số lượng làm cho Kho Lẻ xuống dưới 0.",
    confirmIssue: "Submit",
    currentBasket: "Giỏ hàng hiện tại",
    outboundHistory: "Lịch sử xuất hàng",
    basketEmpty: "Chưa có sản phẩm nào trong giỏ hàng.",
    remove: "Bỏ khỏi giỏ",
    clearBasket: "Xóa toàn bộ giỏ",
    totalBasketItems: "Tổng số lượng",
    searchPrompt: "Bấm tìm để hiển thị sản phẩm.",
    noProductMatches: "Không có sản phẩm nào khớp nội dung tìm kiếm.",
    noProductsRows: "Chưa có sản phẩm nào trong Neon.",
    exceedsStockMessage: "Số lượng vượt quá tồn kho hiện có.",
    addedToBasketMessage: "Đã thêm vào giỏ hàng.",
    selectWarehouseForBasket: "Hãy chọn kho trước khi thêm vào giỏ hàng.",
    loginTitle: "Đăng nhập",
    loginBody: "Bắt buộc đăng nhập trước khi dùng ứng dụng.",
    username: "Tên đăng nhập",
    password: "Mật khẩu",
    signIn: "Đăng nhập",
    signingIn: "Đang đăng nhập...",
    submit: "Submit",
    submitting: "Đang gửi...",
    manageUsersTitle: "Quản lý người dùng",
    adminOnly: "Chỉ quản trị",
    createUser: "Tạo người dùng",
    email: "Email",
    contact: "Liên hệ",
    phone: "Điện thoại",
    address: "Địa chỉ",
    actions: "Thao tác",
    update: "Cập nhật",
    updateSupplier: "Cập nhật nhà cung cấp",
    contactPerson: "Người liên hệ",
    role: "Vai trò",
    saveUser: "Submit",
    created: "Ngày tạo",
    resetPassword: "Đặt lại mật khẩu",
    resetPasswordButton: "Thiết lập mật khẩu mới",
    newPasswordPlaceholder: "Nhập mật khẩu tạm thời",
    loginIdPlaceholder: "Mã đăng nhập",
    temporaryPasswordPlaceholder: "Mật khẩu tạm thời",
    enterProductName: "Nhập tên sản phẩm",
    enterSupplierName: "Nhập tên nhà cung cấp",
    contactPersonPlaceholder: "Người liên hệ",
    phoneNumberPlaceholder: "Số điện thoại",
    emailAddressPlaceholder: "Địa chỉ email",
    basicSupplierAddressPlaceholder: "Địa chỉ cơ bản của nhà cung cấp",
    productImageUpload: "Tải ảnh sản phẩm",
    selectSupplier: "Chọn nhà cung cấp",
    noSuppliersRows: "Chưa có nhà cung cấp nào trong Neon.",
    usernameTaken: "Tên đăng nhập này đã tồn tại.",
    productCreateSuccess: "Lưu sản phẩm thành công.",
    productCreateError: "Không thể lưu sản phẩm.",
    supplierCreateSuccess: "Lưu nhà cung cấp thành công.",
    supplierCreateError: "Không thể lưu nhà cung cấp.",
    supplierUpdateSuccess: "Cập nhật nhà cung cấp thành công.",
    supplierUpdateError: "Không thể cập nhật nhà cung cấp.",
    userCreateSuccess: "Lưu người dùng thành công.",
    userCreateError: "Không thể lưu người dùng.",
    passwordResetSuccess: "Cập nhật mật khẩu thành công.",
    passwordResetError: "Không thể cập nhật mật khẩu.",
    edit: "Edit",
    updateProduct: "Cập nhật sản phẩm",
    updateProductSuccess: "Cập nhật sản phẩm thành công.",
    updateProductError: "Không thể cập nhật sản phẩm.",
    invalidImageMessage: "Tệp hình ảnh không hợp lệ.",
    inboundSubmitSuccess: "Gửi lô nhập kho thành công.",
    inboundSubmitError: "Không thể gửi lô nhập kho.",
    basketSubmitSuccess: "Xuất hàng thành công.",
    basketSubmitError: "Không thể xuất hàng.",
    basketStockError: "Có sản phẩm vượt quá tồn kho hiện có.",
  },
} as const;

export async function getUiPreferences() {
  const cookieStore = await cookies();
  const themeCookie = cookieStore.get(uiCookieNames.theme)?.value ?? cookieStore.get(legacyUiCookieNames.theme)?.value;
  const languageCookie = cookieStore.get(uiCookieNames.language)?.value ?? cookieStore.get(legacyUiCookieNames.language)?.value;
  const theme: UiTheme = themeCookie === "dark" ? "dark" : "light";
  const language: UiLanguage = languageCookie === "vi" ? "vi" : "en";

    return {
    theme,
    language,
    };
}

export async function getUiContext() {
  const preferences = await getUiPreferences();

  return {
    ...preferences,
    text: dictionaries[preferences.language],
  };
}

