import { getProductRows, getSuppliers } from "@/lib/warehouse-data";

export default async function ProductsPage() {
  const [products, suppliers] = await Promise.all([getProductRows(), getSuppliers()]);

  return (
    <div className="grid gap-6">
      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between">
          <div>
            <p className="text-sm font-medium text-slate-500">Catalog management</p>
            <h1 className="text-2xl font-semibold text-slate-950">Products</h1>
          </div>
          <div className="grid gap-3 md:grid-cols-4 lg:w-[760px]">
            <input className="rounded-xl border border-slate-300 px-4 py-3 text-sm outline-none transition focus:border-cyan-500" placeholder="Search product or SKU" />
            <select className="rounded-xl border border-slate-300 px-4 py-3 text-sm outline-none transition focus:border-cyan-500">
              <option>All suppliers</option>
              {suppliers.map((supplier) => (
                <option key={supplier.id}>{supplier.name}</option>
              ))}
            </select>
            <label className="flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-medium text-slate-700">
              <input type="checkbox" className="h-4 w-4 rounded border-slate-300" />
              Include inactive
            </label>
            <button type="button" className="rounded-xl bg-cyan-600 px-4 py-3 text-sm font-semibold text-white transition hover:bg-cyan-500">
              Search
            </button>
          </div>
        </div>

        <div className="mt-5 overflow-hidden rounded-2xl border border-slate-200">
          <table className="min-w-full divide-y divide-slate-200 text-left text-sm">
            <thead className="bg-slate-50 text-slate-500">
              <tr>
                <th className="px-4 py-3 font-medium">SKU</th>
                <th className="px-4 py-3 font-medium">Product</th>
                <th className="px-4 py-3 font-medium">Supplier</th>
                <th className="px-4 py-3 font-medium">Status</th>
                <th className="px-4 py-3 font-medium">kho tong</th>
                <th className="px-4 py-3 font-medium">kho le</th>
                <th className="px-4 py-3 font-medium">Total</th>
                <th className="px-4 py-3 font-medium">Basket</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 bg-white">
              {products.length === 0 ? (
                <tr>
                  <td colSpan={8} className="px-4 py-10 text-center text-sm text-slate-500">
                    No products in Neon yet.
                  </td>
                </tr>
              ) : products.map((product) => {
                return (
                  <tr key={product.id}>
                    <td className="px-4 py-3 font-medium text-slate-900">{product.sku}</td>
                    <td className="px-4 py-3">
                      <div className="font-medium text-slate-900">{product.name}</div>
                      <div className="text-xs text-slate-500">{product.isObsolete ? "Obsolete" : "Current catalog"}</div>
                    </td>
                    <td className="px-4 py-3 text-slate-600">{product.supplierName}</td>
                    <td className="px-4 py-3">
                      <span className={`rounded-full px-3 py-1 text-xs font-semibold ${product.status === "ACTIVE" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>
                        {product.status === "ACTIVE" ? "Active" : "Inactive"}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-slate-600">{product.khoTongQty}</td>
                    <td className="px-4 py-3 text-slate-600">{product.khoLeQty}</td>
                    <td className="px-4 py-3 font-semibold text-slate-900">{product.totalQty}</td>
                    <td className="px-4 py-3">
                      <button type="button" className="rounded-lg border border-cyan-200 bg-cyan-50 px-3 py-2 text-xs font-semibold text-cyan-800 transition hover:bg-cyan-100">
                        Add to basket
                      </button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </section>

      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <div className="flex items-center justify-between">
          <div>
            <p className="text-sm font-medium text-slate-500">Create product</p>
            <h2 className="text-xl font-semibold text-slate-950">New catalog item</h2>
          </div>
          <div className="rounded-full bg-slate-100 px-4 py-2 text-sm font-medium text-slate-700">
            SKU is auto-generated by system
          </div>
        </div>
        <form className="mt-5 grid gap-4 lg:grid-cols-2">
          <label className="grid gap-2 text-sm font-medium text-slate-700">
            Product name
            <input className="rounded-xl border border-slate-300 px-4 py-3 outline-none transition focus:border-cyan-500" placeholder="Enter product name" />
          </label>
          <label className="grid gap-2 text-sm font-medium text-slate-700">
            Supplier
            <select className="rounded-xl border border-slate-300 px-4 py-3 outline-none transition focus:border-cyan-500">
              <option>Select supplier</option>
              {suppliers.map((supplier) => (
                <option key={supplier.id}>{supplier.name}</option>
              ))}
            </select>
          </label>
          <label className="grid gap-2 text-sm font-medium text-slate-700 lg:col-span-2">
            Product image
            <input type="file" className="rounded-xl border border-dashed border-slate-300 bg-slate-50 px-4 py-3 text-sm" />
          </label>
          <label className="flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-medium text-slate-700">
            <input type="checkbox" className="h-4 w-4 rounded border-slate-300" defaultChecked />
            Active product
          </label>
          <label className="flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-medium text-slate-700">
            <input type="checkbox" className="h-4 w-4 rounded border-slate-300" />
            Mark as obsolete
          </label>
          <div className="lg:col-span-2">
            <button type="button" className="rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white transition hover:bg-slate-800">
              Save product
            </button>
          </div>
        </form>
      </section>
    </div>
  );
}
